/**
 * QMC decoder (QQ Music cache) — pure JS, no native deps.
 *
 * Supported formats: .qmc0, .qmc3, .qmcflac, .qmcogg
 *   - .qmc0 / .qmc3  → MP3
 *   - .qmcflac       → FLAC
 *   - .qmcogg        → OGG
 *
 * These are "headerless" QMC files (no QMCv2/STag/QTag markers). The whole
 * file is XOR'd with a deterministic keystream generated by a 8×7 state
 * machine plus a 0x8000-position skip.
 *
 * Algorithm references (all three agree for files up to 64 bytes):
 *   - presburger/qmc-decoder (C++, MIT)        github.com/presburger/qmc-decoder
 *   - bczhc/qmc-decrypt       (Rust, MIT/Apache) github.com/bczhc/qmc-decrypt
 *   - Cross-checked manually against the C++ state machine output
 *
 * NOTE: This implementation matches the C++ state machine (presburger).
 * The Rust implementation differs after byte 64 (it uses a 64-byte table
 * with mirror; the C++ uses a 128-byte period). For typical QMC files
 * (3–10 MB) the algorithms diverge for the entire bulk of the file.
 * We chose the C++ variant because:
 *   1. It has the explicit 0x8000-position skip logic, suggesting the
 *      author reverse-engineered it from a real QQ Music client.
 *   2. presburger/qmc-decoder is the highest-starred public implementation
 *      (2.2K+ stars, 397 forks).
 *   3. The state machine is more "defensive" against periodicity attacks.
 *
 * For QMCv2 (files with "QMCv2" / "STag" / "QTag" markers), the encryption
 * uses a per-file ekey extracted from the QQ Music client. Those formats
 * are NOT supported here.
 */
const fs = require('node:fs');
const path = require('node:path');

// 8 rows × 7 columns. Index with [y][x]. x traverses -1..7 in a snake
// pattern; x = -1 and x = 7 are the "boundary" positions that emit
// fixed values 0xc3 / 0xd8 respectively.
const SEED_MAP = [
  [0x4a, 0xd6, 0xca, 0x90, 0x67, 0xf7, 0x52], // y=0
  [0x5e, 0x95, 0x23, 0x9f, 0x13, 0x11, 0x7e], // y=1
  [0x47, 0x74, 0x3d, 0x90, 0xaa, 0x3f, 0x51], // y=2
  [0xc6, 0x09, 0xd5, 0x9f, 0xfa, 0x66, 0xf9], // y=3
  [0xf3, 0xd6, 0xa1, 0x90, 0xa0, 0xf7, 0xf0], // y=4
  [0x1d, 0x95, 0xde, 0x9f, 0x84, 0x11, 0xf4], // y=5
  [0x0e, 0x74, 0xbb, 0x90, 0xbc, 0x3f, 0x92], // y=6
  [0x00, 0x09, 0x5b, 0x9f, 0x62, 0x66, 0xa1], // y=7
];

// Input extension → output extension
const EXT_MAP = {
  '.qmc0': 'mp3',
  '.qmc3': 'mp3',
  '.qmcflac': 'flac',
  '.qmcogg': 'ogg',
};

class QmcSeed {
  constructor() {
    this.x = -1;
    this.y = 8;
    this.dx = 1;
    this.index = -1;
  }

  nextMask() {
    let ret;
    this.index++;
    if (this.x < 0) {
      this.dx = 1;
      this.y = (8 - this.y) % 8;
      ret = 0xc3;
    } else if (this.x > 6) {
      this.dx = -1;
      this.y = 7 - this.y;
      ret = 0xd8;
    } else {
      ret = SEED_MAP[this.y][this.x];
    }
    this.x += this.dx;
    if (this.index === 0x8000 || (this.index > 0x8000 && (this.index + 1) % 0x8000 === 0)) {
      return this.nextMask();
    }
    return ret;
  }
}

/**
 * Decrypt a QMC file in-place. Returns a Buffer of the decrypted bytes.
 * Pure function — does not touch the filesystem.
 */
function decryptBuffer(qmcBuf) {
  const seed = new QmcSeed();
  const out = Buffer.allocUnsafe(qmcBuf.length);
  for (let i = 0; i < qmcBuf.length; i++) {
    out[i] = qmcBuf[i] ^ seed.nextMask();
  }
  return out;
}

function decodeFile(inputPath, outputDir) {
  const ext = path.extname(inputPath).toLowerCase();
  const outExt = EXT_MAP[ext];
  if (!outExt) {
    throw new Error(`QMC: unsupported extension ${ext}`);
  }
  const input = fs.readFileSync(inputPath);
  const audio = decryptBuffer(input);

  const base = inputPath.replace(/\.[^./]+$/, '');
  const name = base.split(/[\\/]/).pop();
  const outName = `${name}.${outExt}`;
  const outPath = outputDir ? path.join(outputDir, outName) : `${base}.${outExt}`;
  fs.mkdirSync(outputDir || '.', { recursive: true });
  fs.writeFileSync(outPath, audio);
  return { outputPath: outPath, format: outExt };
}

module.exports = {
  decryptBuffer,
  decodeFile,
  QmcSeed,
  SEED_MAP,
  EXT_MAP,
};
