'use strict';

/**
 * End-to-end pipeline tests (worker-thread decode + ffmpeg), using the
 * synthetic encrypted fixtures generated by the other test files.
 */
const { test } = require('node:test');
const assert = require('node:assert');
const { execFileSync } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const pipeline = require('../src/main/pipeline');
const qmc = require('../src/decoders/qmc');

const OUT_DIR = path.join(__dirname, 'output', 'pipeline');
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

function haveFfmpeg() {
  try { execFileSync('ffmpeg', ['-version'], { stdio: 'pipe' }); return true; } catch { return false; }
}
const skipNoFfmpeg = !haveFfmpeg() && 'ffmpeg not available';

function makeMp3(dest, seconds = 2) {
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', `sine=frequency=440:duration=${seconds}`, '-ac', '1', '-ar', '22050',
    '-c:a', 'libmp3lame', '-b:a', '64k', '-metadata', 'title=Original Title', dest], { stdio: 'pipe' });
  return fs.readFileSync(dest);
}

// QMCv1 is a fixed XOR mask, so encrypt == decrypt.
function makeQmc0(mp3Bytes, dest) {
  fs.writeFileSync(dest, qmc.decryptV1Buffer(mp3Bytes));
}

function probeTags(file) {
  return execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=codec_type:format_tags=title', '-of', 'default=noprint_wrappers=1', file], { stdio: 'pipe' }).toString();
}

// Copied from tests/ncm.test.js (that file runs tests on require, so it is not a helper module).
const CORE_KEY = Buffer.from('687A4852416D736F356B496E62617857', 'hex');
const META_KEY = Buffer.from('2331346C6A6B5F215C5D2630553C2728', 'hex');
const PREFIX = Buffer.from('neteasecloudmusic', 'ascii');

function aesEcbEncrypt(block, key) {
  const c = crypto.createCipheriv('aes-128-ecb', key, null);
  c.setAutoPadding(false);
  return Buffer.concat([c.update(block), c.final()]);
}
function pkcs7Pad(buf) {
  const pad = 16 - (buf.length % 16);
  return Buffer.concat([buf, Buffer.alloc(pad, pad)]);
}
function buildRc4Sbox(key) {
  const S = Buffer.alloc(256);
  for (let i = 0; i < 256; i++) S[i] = i;
  let j = 0;
  for (let i = 0; i < 256; i++) {
    j = (j + S[i] + key[i % key.length]) & 0xff;
    const tmp = S[i]; S[i] = S[j]; S[j] = tmp;
  }
  return S;
}
function rc4Transform(S, data) {
  const k = Buffer.alloc(256);
  for (let i = 0; i < 256; i++) k[i] = S[(S[i] + S[(i + S[i]) & 0xff]) & 0xff];
  const out = Buffer.alloc(data.length);
  for (let i = 0; i < data.length; i++) out[i] = data[i] ^ k[(i + 1) % 256];
  return out;
}
function u32(n) { const b = Buffer.alloc(4); b.writeUInt32LE(n); return b; }

function buildSyntheticNcm(audio, metaObj, image) {
  const rc4Key = crypto.randomBytes(16);
  let keyEnc = aesEcbEncrypt(pkcs7Pad(Buffer.concat([PREFIX, rc4Key])), CORE_KEY);
  for (let i = 0; i < keyEnc.length; i++) keyEnc[i] ^= 0x64;

  let metaBlock = Buffer.alloc(0);
  if (metaObj) {
    const json = Buffer.from('music:' + JSON.stringify(metaObj), 'utf8');
    const enc = aesEcbEncrypt(pkcs7Pad(json), META_KEY).toString('base64');
    metaBlock = Buffer.from('163 key(Don\'t modify):' + enc, 'utf8');
    for (let i = 0; i < metaBlock.length; i++) metaBlock[i] ^= 0x63;
  }
  const img = image || Buffer.alloc(0);
  return {
    ncm: Buffer.concat([
      Buffer.from('CTENFDAM', 'ascii'), Buffer.alloc(2), u32(keyEnc.length), keyEnc,
      u32(metaBlock.length), metaBlock, Buffer.alloc(5),
      u32(img.length), u32(img.length), img,
      rc4Transform(buildRc4Sbox(rc4Key), audio),
    ]),
  };
}

test('pipeline: plain audio with same container is copied, not re-encoded', { skip: skipNoFfmpeg }, async () => {
  const src = path.join(OUT_DIR, 'plain.mp3');
  const bytes = makeMp3(src);
  const out = path.join(OUT_DIR, 'copy');
  const stages = [];
  const r = await pipeline.convertOne({ inputPath: src, outputDir: out, format: 'mp3', onProgress: (p) => stages.push(p.stage) });
  assert.strictEqual(r.reencoded, false);
  assert.ok(fs.readFileSync(r.outputPath).equals(bytes), 'byte-identical copy');
  assert.deepStrictEqual(stages, ['done']);
});

test('pipeline: plain audio is re-encoded to a different container with tags preserved', { skip: skipNoFfmpeg }, async () => {
  const src = path.join(OUT_DIR, 'plain2.mp3');
  makeMp3(src);
  const r = await pipeline.convertOne({ inputPath: src, outputDir: path.join(OUT_DIR, 'reenc'), format: 'flac' });
  assert.strictEqual(r.reencoded, true);
  assert.ok(r.outputPath.endsWith('plain2.flac'));
  assert.match(probeTags(r.outputPath), /TAG:title=Original Title/i);
});

test('pipeline: encrypted qmc0 → decrypt in worker → mp3 (no re-encode when container matches)', { skip: skipNoFfmpeg }, async () => {
  const mp3 = makeMp3(path.join(OUT_DIR, 'src3.mp3'));
  const enc = path.join(OUT_DIR, 'song.qmc0');
  makeQmc0(mp3, enc);
  const stages = [];
  const r = await pipeline.convertOne({ inputPath: enc, outputDir: path.join(OUT_DIR, 'dec'), format: 'mp3', onProgress: (p) => stages.push(p.stage) });
  assert.strictEqual(r.reencoded, false);
  assert.ok(fs.readFileSync(r.outputPath).equals(mp3), 'decrypted bytes must equal the original mp3');
  assert.deepStrictEqual(stages, ['decrypt', 'done']);
});

test('pipeline: encrypted qmc0 → flac re-encode removes the intermediate and reports encode progress', { skip: skipNoFfmpeg }, async () => {
  const mp3 = makeMp3(path.join(OUT_DIR, 'src4.mp3'), 3);
  const enc = path.join(OUT_DIR, 'song4.qmc0');
  makeQmc0(mp3, enc);
  const outDir = path.join(OUT_DIR, 'dec-flac');
  const seen = [];
  const r = await pipeline.convertOne({ inputPath: enc, outputDir: outDir, format: 'flac', onProgress: (p) => seen.push(p) });
  assert.ok(r.outputPath.endsWith('song4.flac'));
  assert.ok(!fs.existsSync(path.join(outDir, 'song4.mp3')), 'intermediate must be removed');
  assert.ok(seen.some((p) => p.stage === 'encode' && typeof p.percent === 'number'));
  assert.strictEqual(seen[seen.length - 1].stage, 'done');
});

test('pipeline: unsupported extension throws a clear error', async () => {
  const bogus = path.join(OUT_DIR, 'file.xyz');
  fs.writeFileSync(bogus, 'nope');
  await assert.rejects(pipeline.convertOne({ inputPath: bogus, outputDir: OUT_DIR, format: 'mp3' }), /No decoder for file/);
});

test('pipeline: corrupt encrypted input surfaces the decoder error from the worker', async () => {
  const bad = path.join(OUT_DIR, 'bad.ncm');
  fs.writeFileSync(bad, crypto.randomBytes(512));
  await assert.rejects(pipeline.convertOne({ inputPath: bad, outputDir: OUT_DIR, format: 'mp3' }), /Decryption failed: .*CTENFDAM/);
});

test('pipeline: pre-aborted signal rejects with "aborted"', async () => {
  const src = path.join(OUT_DIR, 'abort.qmc0');
  fs.writeFileSync(src, Buffer.alloc(1024));
  const c = new AbortController();
  c.abort();
  await assert.rejects(pipeline.convertOne({ inputPath: src, outputDir: OUT_DIR, format: 'mp3', signal: c.signal }), /aborted/);
});

test('pipeline: ncm lyric hit writes sibling .lrc and still succeeds', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-hit-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 1406472218 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-hit.ncm');
  fs.writeFileSync(ncmPath, file);

  const lyricsRoot = path.join(OUT_DIR, 'lyrics-hit');
  fs.mkdirSync(path.join(lyricsRoot, 'LrcDownload'), { recursive: true });
  const nested = '{"t":0,"c":[{"tx":"Hello "}]}\n{"t":1230,"c":[{"tx":"World"}]}';
  fs.writeFileSync(path.join(lyricsRoot, 'LrcDownload', '1406472218'), JSON.stringify({ lrc: nested }));

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-hit-out'), format: 'mp3', ncmLyricsDir: lyricsRoot,
    listRoots: () => [],
  });
  const lrcPath = r.outputPath.replace(/\.mp3$/, '.lrc');
  assert.ok(fs.existsSync(r.outputPath));
  const text = fs.readFileSync(lrcPath, 'utf8');
  assert.match(text, /^\[\d{2}:\d{2}/);
});

test('pipeline: ncm lyric miss does not fail conversion or write .lrc', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-miss-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 1406472218 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-miss.ncm');
  fs.writeFileSync(ncmPath, file);

  const emptyRoot = path.join(OUT_DIR, 'lyrics-empty');
  fs.mkdirSync(emptyRoot, { recursive: true });

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-miss-out'), format: 'mp3', ncmLyricsDir: emptyRoot,
    fetchJson: async () => null,
    listRoots: () => [],
  });
  assert.ok(fs.existsSync(r.outputPath));
  assert.ok(!fs.existsSync(r.outputPath.replace(/\.mp3$/, '.lrc')));
});

test('pipeline: lyrics disabled writes no lrc even when cache exists', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-off-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 1406472218 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-off.ncm');
  fs.writeFileSync(ncmPath, file);

  const lyricsRoot = path.join(OUT_DIR, 'lyrics-off');
  fs.mkdirSync(path.join(lyricsRoot, 'LrcDownload'), { recursive: true });
  fs.writeFileSync(path.join(lyricsRoot, 'LrcDownload', '1406472218'), JSON.stringify({ lrc: '[00:00.00]Off' }));

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-off-out'), format: 'mp3',
    ncmLyricsEnabled: false, ncmLyricsDir: lyricsRoot, listRoots: () => [],
  });
  const lrcPath = r.outputPath.replace(/\.mp3$/, '.lrc');
  assert.ok(fs.existsSync(r.outputPath));
  assert.ok(!fs.existsSync(lrcPath));
});

test('pipeline: http miss still succeeds', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-http-miss-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 1406472218 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-http-miss.ncm');
  fs.writeFileSync(ncmPath, file);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-http-miss-out'), format: 'mp3',
    ncmLyricsEnabled: true,
    fetchJson: async () => null,
    listRoots: () => [],
  });
  assert.ok(fs.existsSync(r.outputPath));
  assert.ok(!fs.existsSync(r.outputPath.replace(/\.mp3$/, '.lrc')));
});

test('pipeline: fetchJson hit writes sibling lrc and embeds mp3 tags', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-http-hit-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 424242 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-http-hit.ncm');
  fs.writeFileSync(ncmPath, file);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-http-hit-out'), format: 'mp3',
    ncmLyricsEnabled: true,
    fetchJson: async () => '{"lrc":{"lyric":"[00:00.00]FromNet"}}',
    listRoots: () => [],
  });
  const lrcPath = r.outputPath.replace(/\.mp3$/, '.lrc');
  assert.ok(fs.existsSync(r.outputPath));
  assert.strictEqual(fs.readFileSync(lrcPath, 'utf8').trim(), '[00:00.00]FromNet');
  const probe = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'format_tags=title,artist,album,lyrics',
    '-of', 'default=noprint_wrappers=1', r.outputPath,
  ], { stdio: 'pipe' }).toString();
  assert.match(probe, /TAG:title=Sine Test/i);
  assert.match(probe, /TAG:artist=Synth \/ Wave/i);
  assert.match(probe, /TAG:album=Unit Tests/i);
  assert.match(probe, /TAG:lyrics=\[00:00\.00\]FromNet/i);
});

test('pipeline: wav writes sibling lrc without embedding lyrics', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-wav-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 424243 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-wav.ncm');
  fs.writeFileSync(ncmPath, file);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-wav-out'), format: 'wav',
    ncmLyricsEnabled: true,
    fetchJson: async () => '{"lrc":{"lyric":"[00:00.00]WavOnly"}}',
    listRoots: () => [],
  });
  const lrcPath = r.outputPath.replace(/\.wav$/, '.lrc');
  assert.ok(fs.existsSync(r.outputPath));
  assert.strictEqual(fs.readFileSync(lrcPath, 'utf8').trim(), '[00:00.00]WavOnly');
  const probe = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'format_tags',
    '-of', 'default=noprint_wrappers=1', r.outputPath,
  ], { stdio: 'pipe' }).toString();
  assert.match(probe, /TAG:title=Sine Test/i);
  assert.ok(!/TAG:lyrics=/i.test(probe));
});

test('pipeline: flac re-encode embeds lyrics via ffmetadata', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-flac-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 424244 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-flac.ncm');
  fs.writeFileSync(ncmPath, file);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-flac-out'), format: 'flac',
    ncmLyricsEnabled: true,
    fetchJson: async () => '{"lrc":{"lyric":"[00:00.00]FlacNet"}}',
    listRoots: () => [],
  });
  assert.ok(fs.existsSync(r.outputPath));
  assert.strictEqual(fs.readFileSync(r.outputPath.replace(/\.flac$/, '.lrc'), 'utf8').trim(), '[00:00.00]FlacNet');
  const probe = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'format_tags=title,artist,album,lyrics',
    '-of', 'default=noprint_wrappers=1', r.outputPath,
  ], { stdio: 'pipe' }).toString();
  assert.match(probe, /TAG:title=Sine Test/i);
  assert.match(probe, /TAG:lyrics=\[00:00\.00\]FlacNet/i);
});

test('pipeline: re-encode embed failure still writes lrc and succeeds', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-reenc-fail-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 424245 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-reenc-fail.ncm');
  fs.writeFileSync(ncmPath, file);

  const binDir = path.join(OUT_DIR, 'ncm-lyric-reenc-fail-bin');
  fs.mkdirSync(binDir, { recursive: true });
  const realFfmpeg = execFileSync('sh', ['-c', 'command -v ffmpeg'], { encoding: 'utf8' }).trim();
  const callLog = path.join(binDir, 'calls.log');
  const ffmpegBin = path.join(binDir, 'ffmpeg');
  fs.writeFileSync(ffmpegBin, `#!/bin/sh
printf '%s\\n' "$@" >> '${callLog}'
echo --- >> '${callLog}'
for a in "$@"; do
  case "$a" in
    *.ffmetadata) exit 1 ;;
  esac
done
exec '${realFfmpeg.replace(/'/g, `'\\''`)}' "$@"
`);
  fs.chmodSync(ffmpegBin, 0o755);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-reenc-fail-out'), format: 'flac',
    ncmLyricsEnabled: true, ffmpegBin,
    fetchJson: async () => '{"lrc":{"lyric":"[00:00.00]RetryOk"}}',
    listRoots: () => [],
  });
  assert.ok(fs.existsSync(r.outputPath));
  assert.strictEqual(fs.readFileSync(r.outputPath.replace(/\.flac$/, '.lrc'), 'utf8').trim(), '[00:00.00]RetryOk');
  const log = fs.readFileSync(callLog, 'utf8');
  const runs = log.split('\n---\n').filter((block) => block.includes('-i'));
  assert.ok(runs.length >= 2, 'embed fail must retry transcode');
  assert.ok(runs[0].includes('.ffmetadata'));
  assert.ok(!runs[1].includes('.ffmetadata'));
  const probe = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'format_tags=title,lyrics',
    '-of', 'default=noprint_wrappers=1', r.outputPath,
  ], { stdio: 'pipe' }).toString();
  assert.match(probe, /TAG:title=Sine Test/i);
  assert.ok(!/TAG:lyrics=/i.test(probe));
});

test('pipeline: same-format remux embed failure retries without lyrics file', { skip: skipNoFfmpeg }, async () => {
  const audio = makeMp3(path.join(OUT_DIR, 'ncm-lyric-remux-fail-src.mp3'));
  const meta = { musicName: 'Sine Test', artist: [['Synth', 1], ['Wave', 2]], album: 'Unit Tests', format: 'mp3', musicId: 424246 };
  const { ncm: file } = buildSyntheticNcm(audio, meta, null);
  const ncmPath = path.join(OUT_DIR, 'ncm-lyric-remux-fail.ncm');
  fs.writeFileSync(ncmPath, file);

  const binDir = path.join(OUT_DIR, 'ncm-lyric-remux-fail-bin');
  fs.mkdirSync(binDir, { recursive: true });
  const realFfmpeg = execFileSync('sh', ['-c', 'command -v ffmpeg'], { encoding: 'utf8' }).trim();
  const callLog = path.join(binDir, 'calls.log');
  const ffmpegBin = path.join(binDir, 'ffmpeg');
  fs.writeFileSync(ffmpegBin, `#!/bin/sh
printf '%s\\n' "$@" >> '${callLog}'
echo --- >> '${callLog}'
for a in "$@"; do
  case "$a" in
    *.ffmetadata) exit 1 ;;
  esac
done
exec '${realFfmpeg.replace(/'/g, `'\\''`)}' "$@"
`);
  fs.chmodSync(ffmpegBin, 0o755);

  const r = await pipeline.convertOne({
    inputPath: ncmPath, outputDir: path.join(OUT_DIR, 'ncm-lyric-remux-fail-out'), format: 'mp3',
    ncmLyricsEnabled: true, ffmpegBin,
    fetchJson: async () => '{"lrc":{"lyric":"[00:00.00]RemuxRetry"}}',
    listRoots: () => [],
  });
  assert.ok(fs.existsSync(r.outputPath));
  assert.strictEqual(fs.readFileSync(r.outputPath.replace(/\.mp3$/, '.lrc'), 'utf8').trim(), '[00:00.00]RemuxRetry');
  const log = fs.readFileSync(callLog, 'utf8');
  const runs = log.split('\n---\n').filter((block) => block.includes('-i'));
  assert.ok(runs.length >= 2, 'embed fail must retry remux');
  assert.ok(runs[0].includes('.ffmetadata'));
  assert.ok(!runs[1].includes('.ffmetadata'));
  assert.ok(runs[1].includes('-c:a') && runs[1].includes('copy'), 'retry must stay copy remux');
  const remuxProbe = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'format_tags=title,lyrics',
    '-of', 'default=noprint_wrappers=1', r.outputPath,
  ], { stdio: 'pipe' }).toString();
  assert.match(remuxProbe, /TAG:title=Sine Test/i);
  assert.ok(!/TAG:lyrics=/i.test(remuxProbe));
});
