'use strict';

/**
 * End-to-end pipeline tests (worker-thread decode + ffmpeg), using the
 * synthetic encrypted fixtures generated by the other test files.
 */
const { test } = require('node:test');
const assert = require('node:assert');
const { execFileSync } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const pipeline = require('../src/main/pipeline');
const qmc = require('../src/decoders/qmc');

const OUT_DIR = path.join(__dirname, 'output', 'pipeline');
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

function haveFfmpeg() {
  try { execFileSync('ffmpeg', ['-version'], { stdio: 'pipe' }); return true; } catch { return false; }
}
const skipNoFfmpeg = !haveFfmpeg() && 'ffmpeg not available';

function makeMp3(dest, seconds = 2) {
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', `sine=frequency=440:duration=${seconds}`, '-ac', '1', '-ar', '22050',
    '-c:a', 'libmp3lame', '-b:a', '64k', '-metadata', 'title=Original Title', dest], { stdio: 'pipe' });
  return fs.readFileSync(dest);
}

// QMCv1 is a fixed XOR mask, so encrypt == decrypt.
function makeQmc0(mp3Bytes, dest) {
  fs.writeFileSync(dest, qmc.decryptV1Buffer(mp3Bytes));
}

function probeTags(file) {
  return execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=codec_type:format_tags=title', '-of', 'default=noprint_wrappers=1', file], { stdio: 'pipe' }).toString();
}

test('pipeline: plain audio with same container is copied, not re-encoded', { skip: skipNoFfmpeg }, async () => {
  const src = path.join(OUT_DIR, 'plain.mp3');
  const bytes = makeMp3(src);
  const out = path.join(OUT_DIR, 'copy');
  const stages = [];
  const r = await pipeline.convertOne({ inputPath: src, outputDir: out, format: 'mp3', onProgress: (p) => stages.push(p.stage) });
  assert.strictEqual(r.reencoded, false);
  assert.ok(fs.readFileSync(r.outputPath).equals(bytes), 'byte-identical copy');
  assert.deepStrictEqual(stages, ['done']);
});

test('pipeline: plain audio is re-encoded to a different container with tags preserved', { skip: skipNoFfmpeg }, async () => {
  const src = path.join(OUT_DIR, 'plain2.mp3');
  makeMp3(src);
  const r = await pipeline.convertOne({ inputPath: src, outputDir: path.join(OUT_DIR, 'reenc'), format: 'flac' });
  assert.strictEqual(r.reencoded, true);
  assert.ok(r.outputPath.endsWith('plain2.flac'));
  assert.match(probeTags(r.outputPath), /TAG:title=Original Title/i);
});

test('pipeline: encrypted qmc0 → decrypt in worker → mp3 (no re-encode when container matches)', { skip: skipNoFfmpeg }, async () => {
  const mp3 = makeMp3(path.join(OUT_DIR, 'src3.mp3'));
  const enc = path.join(OUT_DIR, 'song.qmc0');
  makeQmc0(mp3, enc);
  const stages = [];
  const r = await pipeline.convertOne({ inputPath: enc, outputDir: path.join(OUT_DIR, 'dec'), format: 'mp3', onProgress: (p) => stages.push(p.stage) });
  assert.strictEqual(r.reencoded, false);
  assert.ok(fs.readFileSync(r.outputPath).equals(mp3), 'decrypted bytes must equal the original mp3');
  assert.deepStrictEqual(stages, ['decrypt', 'done']);
});

test('pipeline: encrypted qmc0 → flac re-encode removes the intermediate and reports encode progress', { skip: skipNoFfmpeg }, async () => {
  const mp3 = makeMp3(path.join(OUT_DIR, 'src4.mp3'), 3);
  const enc = path.join(OUT_DIR, 'song4.qmc0');
  makeQmc0(mp3, enc);
  const outDir = path.join(OUT_DIR, 'dec-flac');
  const seen = [];
  const r = await pipeline.convertOne({ inputPath: enc, outputDir: outDir, format: 'flac', onProgress: (p) => seen.push(p) });
  assert.ok(r.outputPath.endsWith('song4.flac'));
  assert.ok(!fs.existsSync(path.join(outDir, 'song4.mp3')), 'intermediate must be removed');
  assert.ok(seen.some((p) => p.stage === 'encode' && typeof p.percent === 'number'));
  assert.strictEqual(seen[seen.length - 1].stage, 'done');
});

test('pipeline: unsupported extension throws a clear error', async () => {
  const bogus = path.join(OUT_DIR, 'file.xyz');
  fs.writeFileSync(bogus, 'nope');
  await assert.rejects(pipeline.convertOne({ inputPath: bogus, outputDir: OUT_DIR, format: 'mp3' }), /No decoder for file/);
});

test('pipeline: corrupt encrypted input surfaces the decoder error from the worker', async () => {
  const bad = path.join(OUT_DIR, 'bad.ncm');
  fs.writeFileSync(bad, crypto.randomBytes(512));
  await assert.rejects(pipeline.convertOne({ inputPath: bad, outputDir: OUT_DIR, format: 'mp3' }), /Decryption failed: .*CTENFDAM/);
});

test('pipeline: pre-aborted signal rejects with "aborted"', async () => {
  const src = path.join(OUT_DIR, 'abort.qmc0');
  fs.writeFileSync(src, Buffer.alloc(1024));
  const c = new AbortController();
  c.abort();
  await assert.rejects(pipeline.convertOne({ inputPath: src, outputDir: OUT_DIR, format: 'mp3', signal: c.signal }), /aborted/);
});
