package com.openconverter.app.decoders

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.security.MessageDigest

/**
 * Parity tests: each Kotlin decoder must produce bytes whose SHA-256 matches
 * the JS reference (recorded in `expected-sha256.json`). The fixtures and
 * oracle hashes are generated by `tests/gen-{kwm,kgm,qmc-v1,ncm}-synthetic.js`.
 */
class DecoderParityTest {

    private fun sha256(bytes: ByteArray): String {
        val md = MessageDigest.getInstance("SHA-256")
        return md.digest(bytes).joinToString("") { "%02x".format(it) }
    }

    private fun loadResource(path: String): ByteArray =
        javaClass.classLoader!!.getResourceAsStream(path)!!.use { it.readBytes() }

    private fun resourceExists(path: String): Boolean =
        javaClass.classLoader!!.getResource(path) != null

    private fun loadOracle(dir: String): JSONObject =
        JSONObject(String(loadResource("$dir/expected-sha256.json"), Charsets.UTF_8))

    // ----- KWM -----
    @Test fun kwm_synthetic_matches_js_oracle() {
        val oracle = loadOracle("test-kwm")
        val expectedSha = oracle.getString("synthetic-kwm.kwm")
        val cipher = loadResource("test-kwm/synthetic-kwm.kwm")
        val r = KwmDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    // ----- KGM / KGMA / VPR -----
    @Test fun kgm_synthetic_matches_js_oracle() {
        val oracle = loadOracle("test-kgm")
        val expectedSha = oracle.getString("synthetic-kgm.kgm")
        val cipher = loadResource("test-kgm/synthetic-kgm.kgm")
        val r = KgmDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    @Test fun kgma_synthetic_matches_js_oracle() {
        val oracle = loadOracle("test-kgm")
        val expectedSha = oracle.getString("synthetic-kgma.kgma")
        val cipher = loadResource("test-kgm/synthetic-kgma.kgma")
        val r = KgmDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    @Test fun vpr_synthetic_matches_js_oracle() {
        val oracle = loadOracle("test-kgm")
        val expectedSha = oracle.getString("synthetic-vpr.vpr")
        val cipher = loadResource("test-kgm/synthetic-vpr.vpr")
        val r = KgmDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    // ----- QMC v1 -----
    @Test fun qmcv1_synthetic_matches_js_oracle() {
        val oracle = loadOracle("test-qmc")
        val expectedSha = oracle.getString("synthetic-qmc0.qmc0")
        val cipher = loadResource("test-qmc/synthetic-qmc0.qmc0")
        val r = QmcDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    // ----- NCM (real fixture, AES + RC4) -----
    // Real NCM sample is copyrighted and not tracked in the public repo.
    // When a maintainer drops one into test-ncm/sample.ncm + adds its sha256
    // to expected-sha256.json, this test runs; otherwise it is skipped.
    @Test fun ncm_real_sample_matches_js_oracle() {
        assumeTrue(
            "test-ncm/sample.ncm not present (copyrighted fixture, not tracked)",
            resourceExists("test-ncm/sample.ncm")
        )
        val oracle = loadOracle("test-ncm")
        val expectedSha = oracle.getString("sample.ncm")
        val cipher = loadResource("test-ncm/sample.ncm")
        val r = NcmDecoder.decrypt(cipher)
        assertEquals(expectedSha, sha256(r.audio))
    }

    // ----- Registry wiring -----
    @Test fun default_registry_resolves_all_v1_extensions() {
        val r = DefaultDecoders.registry
        // Every v1 cipher extension must route to a real decoder.
        for (ext in listOf(".ncm", ".kwm", ".kgm", ".kgma", ".vpr",
                           ".qmc0", ".qmc3", ".qmcflac", ".qmcogg")) {
            val d = r.find(ext)
            assertEquals("registry must resolve $ext", true, d != null)
        }
    }
}
