'use strict';

/**
 * KGG encrypted SQLite DB cipher.
 *
 * Reference: 1:1 port of android/.../kgg/KggDatabaseCipher.kt
 * Public algorithm spec — see unlock-music and the KuGou PC client.
 *
 * KGMusicV3.db is an AES-128-CBC encrypted SQLite database. Each
 * 1024-byte page is encrypted with a per-page key + IV derived from
 * the page number:
 *
 *   pageKey(pageN) = MD5(masterKey || pageN_LE_4B || 0x546c4173_LE_4B)
 *   pageIv(pageN)  = MD5(LE_4B(PRNG(pageN + 1)) × 4)
 *
 * The first page also carries a small integrity check (offset 16..24
 * contains a copy of bytes 8..16, used to detect wrong master key).
 */

const crypto = require('node:crypto');

const PAGE_SIZE = 1024;
const SQLITE_HEADER = Buffer.from('SQLite format 3\0', 'ascii');

// Public master key for KGMusicV3.db (per the public algorithm spec).
// This is the AES-128 key KuGou uses to encrypt the key database.
const MASTER_KEY = Buffer.from([
  0x1d, 0x61, 0x31, 0x45, 0xb2, 0x47, 0xbf, 0x7f,
  0x3d, 0x18, 0x96, 0x72, 0x14, 0x4f, 0xe4, 0xbf,
]);

// 0x546c4173 ("sAlT" in ASCII, LE) — domain separation for page key.
const PAGE_KEY_SALT = 0x546c4173;

// 64-bit LCG parameters for the page IV PRNG (matches Kotlin source).
const PRNG_MUL = 0x9ef4n;
const PRNG_DEC = 0xce26n;
const PRNG_MOD = 0x7fffff07n;
const MASK32 = 0xffffffffn;

function pageKey(masterKey, pageNumber) {
  const material = Buffer.alloc(24);
  material.set(masterKey, 0);
  material.writeUInt32LE(pageNumber >>> 0, 16);
  material.writeUInt32LE(PAGE_KEY_SALT >>> 0, 20);
  return crypto.createHash('md5').update(material).digest();
}

function pageIv(pageNumber) {
  // Material: 4 × uint32 LE, generated by the LCG.
  let seed = BigInt(pageNumber) + 1n;
  const material = Buffer.alloc(16);
  for (let i = 0; i < 4; i++) {
    // The Kotlin LCG: value = seed * 0x9ef4 - floor(seed / 0xce26) * 0x7fffff07
    // All arithmetic in 32-bit signed space.
    const value = (seed * PRNG_MUL - (seed / PRNG_DEC) * PRNG_MOD) & MASK32;
    let next;
    if ((value & 0x80000000n) === 0n) {
      next = value;
    } else {
      next = (value + PRNG_MOD) & MASK32;
    }
    seed = next;
    material.writeUInt32LE(Number(next & MASK32), i * 4);
  }
  return crypto.createHash('md5').update(material).digest();
}

function isPlaintextHeader(page) {
  return page.subarray(0, SQLITE_HEADER.length).equals(SQLITE_HEADER);
}

function isEncryptedHeader(page) {
  // The encrypted header layout (per KggDatabaseCipher.kt):
  //   offset 16..19 : LE uint32 reconstructed page size (e.g. 0x400 = 1024)
  //   offset 20..23 : magic 0x20204000 (LE)
  // The page size is reconstructed as (byte16 << 8) | (byte17 << 16) so
  // a 1024-byte page has bytes 16=0x04, 17=0x00.
  const magic = page.readUInt32LE(20);
  if (magic !== 0x20204000) return false;
  const pageSizeLow = page[16] & 0xff;
  const pageSizeHigh = page[17] & 0xff;
  const pageSize = (pageSizeLow << 8) | (pageSizeHigh << 16);
  const diff = pageSize - 0x200;
  if (diff < 0 || diff > 0xfe00) return false;
  return ((pageSize - 1) & pageSize) === 0;
}

function decryptFirstPage(page, masterKey) {
  if (!isEncryptedHeader(page)) {
    throw new Error('Invalid encrypted KGG database header');
  }
  // Save copy of bytes 16..24 (used to verify the round trip below)
  const expectedHeader = Buffer.from(page.subarray(16, 24));
  // Overwrite offset 16..24 with offset 8..16 (the "swap")
  page.copy(page, 16, 8, 16);
  // Decrypt the page (the actual encrypted payload starts at offset 16)
  const decrypted = decryptBlocks(page.subarray(16, PAGE_SIZE), 1, masterKey);
  decrypted.copy(page, 16);
  // After decrypt, bytes 16..24 should match the original 16..24
  if (!page.subarray(16, 24).equals(expectedHeader)) {
    throw new Error('KGG database page 1 integrity check failed (wrong master key?)');
  }
  // Replace the original "encrypted" header with the real SQLite header
  SQLITE_HEADER.copy(page, 0);
}

function decryptBlocks(ciphertext, pageNumber, masterKey) {
  const decipher = crypto.createDecipheriv(
    'aes-128-cbc',
    pageKey(masterKey, pageNumber),
    pageIv(pageNumber),
  );
  decipher.setAutoPadding(false);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]);
}

function decryptPage(page, pageNumber, masterKey) {
  decryptBlocks(page, pageNumber, masterKey).copy(page);
}

/**
 * Decrypt a KGMusicV3.db stream to an output stream.
 *
 * @param {Readable} input
 * @param {Writable} output
 * @param {Buffer} [masterKey] override master key (for testing)
 */
function decryptStream(input, output, masterKey = MASTER_KEY) {
  return new Promise((resolve, reject) => {
    let firstPage = null;
    const chunks = [];
    let collected = 0;

    function readPage() {
      if (collected < PAGE_SIZE) {
        input.once('readable', () => {
          const chunk = input.read();
          if (chunk === null) {
            return reject(new Error('KGMusicV3.db ended before first page'));
          }
          chunks.push(chunk);
          collected += chunk.length;
          if (collected >= PAGE_SIZE) {
            firstPage = Buffer.concat(chunks, collected).subarray(0, PAGE_SIZE);
            chunks.length = 0;
            processFirstPage(firstPage);
          } else {
            readPage();
          }
        });
      }
    }

    function processFirstPage(page) {
      try {
        if (isPlaintextHeader(page)) {
          output.write(page);
          return readNextPage(2, false);
        }
        decryptFirstPage(page, masterKey);
        output.write(page);
        return readNextPage(2, true);
      } catch (err) {
        return reject(err);
      }
    }

    function readNextPage(pageNumber, encrypted) {
      let buf = null;
      const inner = [];
      let acc = 0;
      function more() {
        if (acc >= PAGE_SIZE) {
          buf = Buffer.concat(inner, acc).subarray(0, PAGE_SIZE);
          try {
            if (encrypted) decryptPage(buf, pageNumber, masterKey);
            output.write(buf);
            return readNextPage(pageNumber + 1, encrypted);
          } catch (err) {
            return reject(err);
          }
        }
        const chunk = input.read();
        if (chunk === null) {
          if (acc > 0) return reject(new Error(`KGMusicV3.db truncated mid-page at page ${pageNumber}`));
          return resolve();
        }
        inner.push(chunk);
        acc += chunk.length;
        more();
      }
      more();
    }

    readPage();
  });
}

module.exports = {
  PAGE_SIZE,
  MASTER_KEY,
  pageKey,
  pageIv,
  isPlaintextHeader,
  isEncryptedHeader,
  decryptStream,
};
